### ISSUE TITLE
Alarms

### ISSUE THREAD

**Issue by HrvojeJuric** [altibiz/ozds#16]
### Idea

Add alarm system where system errors and warnings are displayed in the UI. And critical errors are sent to operator representative emails.

### Acceptance criteria

- [x] add events
- [ ] add tracking of which events were witnessed
- [ ] add email sending of critical events
- [x] add more tasks once the dust has settled on what needs to be implemented
- [ ] alarm when measurement thresholds are overcome
- [ ] add system documentation
- [x] add events for each data model mutate page
- [x] add bell icon near user icon with active red priority events
- [x] add alerm table ordered by date and priority
- [ ] add event seen button for relevant events

### Implementation

Separate events table that keeps track of everything that has happened and if it was seen by a responsible person.

**Comment by GabrijelAB** [comment]
- [] MutateEventsTable >remove "Nivo "
- [] MutateEventsTable > add "Author"
