### ISSUE TITLE
Cloud preparation

### ISSUE THREAD

**Issue by HrvojeJuric** [altibiz/ozds#24]
Prepare website for cloud deployment.

- [x] make ui for mutations presentable
- [x] invoice table -> change first column to title
- [x] meter page -> W -> kW
- [x] network user dashboard -> add last calculations
- [x] location dashboard -> current active power (This is messed up)
- [x] fix gray background on invoice print
- [x] graphs need to use 15 min segments when above 1h time span
- [x] graphs draw weird lines when updating
- [x] add savechangesasync() on all mutations
- [x] fix linter warnings
- [x] fix invoices not knowing about measurement locations
- [x] setup github workflow for pr push for format, lint, test
- [x] insert initial data in cloud through ui (locations, network users, meters, ...)
- [x] insert previous measurement data through push api
- [x] warn: Microsoft.EntityFrameworkCore.Query[10102]
      The query uses a row limiting operator ('Skip'/'Take') without an 'OrderBy' operator. This may lead to unpredictable results. If the 'Distinct' operator is used after 'OrderBy', then make sure to use the 'OrderBy' operator after 'Distinct' as the ordering would otherwise get erased.
- [x] don't use savechanges on disposed in mutations (dont miss OzdsLocationMutations and OzdsNetworkUserMutations)

**Comment by GabrijelAB** [comment]
Make all components fetch data dynamically
- [ ] InvoicesTable
- [ ] LocationRepDashboard
- [ ] LocationsTable
- [ ] MetersTable
- [ ] NetUserRepDashboard
- [ ] NetUserRepGraph
- [ ] NetUsersTable

**Comment by GabrijelAB** [comment]
Add Invoice querying

- [] NetUsersTable
- [] LocationsTable
- [] LocationRepDashboard
- [] MetersTable
