### ISSUE TITLE
Project structure documentation

### ISSUE THREAD

**Issue by HrvojeJuric** [altibiz/ozds#25]
### Area

structure

### Description

- [x] Ozds.Business
- [x] Ozds.Data
- [x] Ozds.Client
- [x] Ozds.Server
- [x] Ozds.Fake
- [x] Ozds.Business.Test

**Comment by GabrijelAB** [comment]
### Ozds.Client

- [ ] Pages
- [ ] Shared > Models
- [ ] Shared
- [ ] General flow
- [ ] Differences between representative roles
