### ISSUE TITLE
UI documentation

### ISSUE THREAD

**Issue by HrvojeJuric** [altibiz/ozds#30]
### Area

ui

### Description

Add documentation of the current state of the UI. Describe each page accessible to these actors.

- [x] admin
- [x] login

#### Operator

- [x] representatives
- [x] add pages to document

#### Location

- [x] add pages to document

#### Network user

- [x] dashboard
- [x] add pages to document

#### Other

- [x] meter
- [x] add pages to document

**Comment by HrvojeJuric** [comment]
Oprators:

- [ ] add pages to document

**Comment by GabrijelAB** [comment]
Structure:

For dashboards:

## Navigation

{links to related sites}

## Content

{image of dashboard}

{detailed explanation of image}

For normal pages:

## Available to

{links to dashboards that can access this page}

## Content

{image of page}

{general use of page and list of components}

{image of component}

{detailed explanation of componenet}
