### ISSUE TITLE
TariffUnary returns T1

### ISSUE THREAD

**Issue by HrvojeJuric** [altibiz/ozds#60]
### Problem

![image](https://github.com/altibiz/ozds/assets/96726264/c69b1dfe-d0df-4c19-88f9-23d257864e0d)

ActiveEnergySpan_Wh.SpanMax.TariffUnary.DuplexImport.PhaseSum on SchneideriEM3xxAggregate is
active_energy_total_import_t1_max_wh

### Steps to reproduce

1. login as network user
2. go to meters page

### Acceptance criteria

ActiveEnergySpan_Wh.SpanMax.TariffUnary.DuplexImport.PhaseSum returns T0

### Implementation

check math about TariffUnary

**Comment by GabrijelAB** [comment]
Pronašao sam i problem sa Schnider emasurement-ima.

Ako pokušam dobit measure.ActivePower_W.TariffBinary.T1.DuplexImport.PhaseSum onda mi se uvjek vraća 0 samo za Schnider,
ali ako koristim measure.ActivePower_W.TariffUnary.DuplexImport.PhaseSum onda radi i za Abb i za Schnider
